name: tool
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.0.0
  charcode: ^1.3.1
  glob: ^2.0.2
  image: ^4.2.0
  markdown: ^7.2.2
  mime_type: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.1
  sass: ^1.56.0
  shelf: ^1.3.1
  string_scanner: ^1.1.0
